### ISSUE TITLE
Can't compile Puma33DS

### ISSUE THREAD

**Issue by gnmmarechal** [rboninsegna/Puma33DS#2]
I get this.

```
arm-none-eabi-gcc -Wall -Wextra -MMD -MP -marm -mcpu=arm946e-s -fno-builtin -fshort-wchar -std=c11 -Wno-main -O2 -flto -ffast-math -DCONFIG_TITLE="\"Puma33DS v5.5-c54835f6 configuration\""   -c -o build/config.o source/config.c
source/config.c: In function 'configMenu':
source/config.c:239:38: error: 'PIN_LOCATION' undeclared (first use in this function)
     else if(oldPinStatus) fileDelete(PIN_LOCATION);
                                      ^
source/config.c:239:38: note: each undeclared identifier is reported only once for each function it appears in
Makefile:100: recipe for target 'build/config.o' failed
make: *** [build/config.o] Error 1
```

**Comment by rboninsegna** [comment]
Oh, switch to the previous commit and it'll work :)

I know, that last merge was against my usual workflow, that is, merge and correct only when there are interesting changes -- so since I wasn't releasing, I didn't even try if it was buildable...

**Comment by gnmmarechal** [comment]
Huh. Thanks for the reply! I'm planning on making an updater for Puma33DS (based on StarUpdater and my own Corbenik Updater), but I couldn't because there'd be no point as I'd be unable to compile the nightly x.x.

I no longer own the VPS (I got refunded as I didn't need it anymore) but I'll be moving soon, and I may be able to get one of my laptops to run 24/7 and compile the latest commit. I'll work on the updater then.

**Comment by rboninsegna** [comment]
Well, v8 is out and hopefully this means it was correctly built from source :D

And nice to see someone is showing their interest in this project, so have a tip for when you'll build it yourself: wait a good 15 minutes or so before building as, while compilation is reasonably fast, if I'm still working you'll probably see another commit within that time, and the ones before may be broken in a non-obvious way!

**Comment by gnmmarechal** [comment]
I'll probably have my laptop build twice per day or so.

Well then, time to start making PumaUpdater!

**Comment by gnmmarechal** [comment]
There we go, I've started writing the updater, the bootstrapper is done, I'll probably finish a test version of the script tomorrow.
https://github.com/gnmmarechal/PumaUpdater
